In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('auto-mpg.data',delimiter='\s+',names=['mpg','cylinders','displacement','horsepower','weight','acceleration','model_year','origin','car_name'])

In [ ]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [ ]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
car_name        0
dtype: int64

In [ ]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model_year        int64
origin            int64
car_name         object
dtype: object

In [ ]:
df['horsepower'] = df['horsepower'].astype('float')

ValueError: could not convert string to float: '?'

In [ ]:
#Query Data Frame
df[df['horsepower'] == '?']

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
32,25.0,4,98.0,?,2046.0,19.0,71,1,ford pinto
126,21.0,6,200.0,?,2875.0,17.0,74,1,ford maverick
330,40.9,4,85.0,?,1835.0,17.3,80,2,renault lecar deluxe
336,23.6,4,140.0,?,2905.0,14.3,80,1,ford mustang cobra
354,34.5,4,100.0,?,2320.0,15.8,81,2,renault 18i
374,23.0,4,151.0,?,3035.0,20.5,82,1,amc concord dl

In [ ]:
df.shape

(398, 9)

In [ ]:
df1 = df[df['horsepower'] != '?']

In [ ]:
df1.shape

(392, 9)

In [ ]:
df1.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model_year        int64
origin            int64
car_name         object
dtype: object

In [ ]:
df1['horsepower'] = df1['horsepower'].astype('float')

<ipython-input-20-267a7438b49f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['horsepower'] = df1['horsepower'].astype('float')

In [ ]:
df1.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight          float64
acceleration    float64
model_year        int64
origin            int64
car_name         object
dtype: object

In [ ]:
def example(a):
  return 2 * a

In [ ]:
df['cylinders'] = df['cylinders'].apply(example)

In [ ]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
0,18.0,16,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,16,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,16,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,16,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,16,302.0,140.0,3449.0,10.5,70,1,ford torino

In [ ]:
names = ['mpg','cylinders','displacement','horsepower','weight','acceleration','model_year','origin','car_name']

In [ ]:
df = pd.read_csv('auto-mpg.data',delim_whitespace=True,names=names,na_values='?')

In [ ]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [ ]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
car_name        0
dtype: int64

In [ ]:
df.shape

(398, 9)

In [ ]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight          float64
acceleration    float64
model_year        int64
origin            int64
car_name         object
dtype: object

In [ ]:
df = df.dropna()

In [ ]:
df.shape

(392, 9)

In [ ]:
mean_hp = df['horsepower'].mean()
mean_hp

104.46938775510205

In [ ]:
df['horsepower'].fillna(mean_hp,inplace=True)

In [ ]:
df.shape

(398, 9)

In [ ]:
df[df['horsepower'] == 104.46938775510205]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
32,25.0,4,98.0,104.469388,2046.0,19.0,71,1,ford pinto
126,21.0,6,200.0,104.469388,2875.0,17.0,74,1,ford maverick
330,40.9,4,85.0,104.469388,1835.0,17.3,80,2,renault lecar deluxe
336,23.6,4,140.0,104.469388,2905.0,14.3,80,1,ford mustang cobra
354,34.5,4,100.0,104.469388,2320.0,15.8,81,2,renault 18i
374,23.0,4,151.0,104.469388,3035.0,20.5,82,1,amc concord dl

In [ ]:
for i in df['horsepower']:
  print(i)

130.0
165.0
150.0
150.0
140.0
198.0
220.0
215.0
225.0
190.0
170.0
160.0
150.0
225.0
95.0
95.0
97.0
85.0
88.0
46.0
87.0
90.0
95.0
113.0
90.0
215.0
200.0
210.0
193.0
88.0
90.0
95.0
104.46938775510205
100.0
105.0
100.0
88.0
100.0
165.0
175.0
153.0
150.0
180.0
170.0
175.0
110.0
72.0
100.0
88.0
86.0
90.0
70.0
76.0
65.0
69.0
60.0
70.0
95.0
80.0
54.0
90.0
86.0
165.0
175.0
150.0
153.0
150.0
208.0
155.0
160.0
190.0
97.0
150.0
130.0
140.0
150.0
112.0
76.0
87.0
69.0
86.0
92.0
97.0
80.0
88.0
175.0
150.0
145.0
137.0
150.0
198.0
150.0
158.0
150.0
215.0
225.0
175.0
105.0
100.0
100.0
88.0
95.0
46.0
150.0
167.0
170.0
180.0
100.0
88.0
72.0
94.0
90.0
85.0
107.0
90.0
145.0
230.0
49.0
75.0
91.0
112.0
150.0
110.0
122.0
180.0
95.0
104.46938775510205
100.0
100.0
67.0
80.0
65.0
75.0
100.0
110.0
105.0
140.0
150.0
150.0
140.0
150.0
83.0
67.0
78.0
52.0
61.0
75.0
75.0
75.0
97.0
93.0
67.0
95.0
105.0
72.0
72.0
170.0
145.0
150.0
148.0
110.0
105.0
110.0
95.0
110.0
110.0
129.0
75.0
83.0
100.0
78.0
96.0
71.0
97.0
97.0
70.0
90.0
95.0
88.0
98.0
115.0
53.0
86.0
81.0
92.0
79.0
83.0
140.0
150.0
120.0
152.0
100.0
105.0
81.0
90.0
52.0
60.0
70.0
53.0
100.0
78.0
110.0
95.0
71.0
70.0
75.0
72.0
102.0
150.0
88.0
108.0
120.0
180.0
145.0
130.0
150.0
68.0
80.0
58.0
96.0
70.0
145.0
110.0
145.0
130.0
110.0
105.0
100.0
98.0
180.0
170.0
190.0
149.0
78.0
88.0
75.0
89.0
63.0
83.0
67.0
78.0
97.0
110.0
110.0
48.0
66.0
52.0
70.0
60.0
110.0
140.0
139.0
105.0
95.0
85.0
88.0
100.0
90.0
105.0
85.0
110.0
120.0
145.0
165.0
139.0
140.0
68.0
95.0
97.0
75.0
95.0
105.0
85.0
97.0
103.0
125.0
115.0
133.0
71.0
68.0
115.0
85.0
88.0
90.0
110.0
130.0
129.0
138.0
135.0
155.0
142.0
125.0
150.0
71.0
65.0
80.0
80.0
77.0
125.0
71.0
90.0
70.0
70.0
65.0
69.0
90.0
115.0
115.0
90.0
76.0
60.0
70.0
65.0
90.0
88.0
90.0
90.0
78.0
90.0
75.0
92.0
75.0
65.0
105.0
65.0
48.0
48.0
67.0
67.0
67.0
104.46938775510205
67.0
62.0
132.0
100.0
88.0
104.46938775510205
72.0
84.0
84.0
92.0
110.0
84.0
58.0
64.0
60.0
67.0
65.0
62.0
68.0
63.0
65.0
65.0
74.0
104.46938775510205
75.0
75.0
100.0
74.0
80.0
76.0
116.0
120.0
110.0
105.0
88.0
85.0
88.0
88.0
88.0
85.0
84.0
90.0
92.0
104.46938775510205
74.0
68.0
68.0
63.0
70.0
88.0
75.0
70.0
67.0
67.0
67.0
110.0
85.0
92.0
112.0
96.0
84.0
90.0
86.0
52.0
84.0
79.0
82.0

In [ ]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model_year        int64
origin            int64
car_name         object
dtype: object

In [ ]:
for i in df['horsepower']:
  if isinstance(i,str):
    print(f'found {i}')

found 130.0
found 165.0
found 150.0
found 150.0
found 140.0
found 198.0
found 220.0
found 215.0
found 225.0
found 190.0
found 170.0
found 160.0
found 150.0
found 225.0
found 95.00
found 95.00
found 97.00
found 85.00
found 88.00
found 46.00
found 87.00
found 90.00
found 95.00
found 113.0
found 90.00
found 215.0
found 200.0
found 210.0
found 193.0
found 88.00
found 90.00
found 95.00
found ?
found 100.0
found 105.0
found 100.0
found 88.00
found 100.0
found 165.0
found 175.0
found 153.0
found 150.0
found 180.0
found 170.0
found 175.0
found 110.0
found 72.00
found 100.0
found 88.00
found 86.00
found 90.00
found 70.00
found 76.00
found 65.00
found 69.00
found 60.00
found 70.00
found 95.00
found 80.00
found 54.00
found 90.00
found 86.00
found 165.0
found 175.0
found 150.0
found 153.0
found 150.0
found 208.0
found 155.0
found 160.0
found 190.0
found 97.00
found 150.0
found 130.0
found 140.0
found 150.0
found 112.0
found 76.00
found 87.00
found 69.00
found 86.00
found 92.00
found 97.00
found 80.00
found 88.00
found 175.0
found 150.0
found 145.0
found 137.0
found 150.0
found 198.0
found 150.0
found 158.0
found 150.0
found 215.0
found 225.0
found 175.0
found 105.0
found 100.0
found 100.0
found 88.00
found 95.00
found 46.00
found 150.0
found 167.0
found 170.0
found 180.0
found 100.0
found 88.00
found 72.00
found 94.00
found 90.00
found 85.00
found 107.0
found 90.00
found 145.0
found 230.0
found 49.00
found 75.00
found 91.00
found 112.0
found 150.0
found 110.0
found 122.0
found 180.0
found 95.00
found ?
found 100.0
found 100.0
found 67.00
found 80.00
found 65.00
found 75.00
found 100.0
found 110.0
found 105.0
found 140.0
found 150.0
found 150.0
found 140.0
found 150.0
found 83.00
found 67.00
found 78.00
found 52.00
found 61.00
found 75.00
found 75.00
found 75.00
found 97.00
found 93.00
found 67.00
found 95.00
found 105.0
found 72.00
found 72.00
found 170.0
found 145.0
found 150.0
found 148.0
found 110.0
found 105.0
found 110.0
found 95.00
found 110.0
found 110.0
found 129.0
found 75.00
found 83.00
found 100.0
found 78.00
found 96.00
found 71.00
found 97.00
found 97.00
found 70.00
found 90.00
found 95.00
found 88.00
found 98.00
found 115.0
found 53.00
found 86.00
found 81.00
found 92.00
found 79.00
found 83.00
found 140.0
found 150.0
found 120.0
found 152.0
found 100.0
found 105.0
found 81.00
found 90.00
found 52.00
found 60.00
found 70.00
found 53.00
found 100.0
found 78.00
found 110.0
found 95.00
found 71.00
found 70.00
found 75.00
found 72.00
found 102.0
found 150.0
found 88.00
found 108.0
found 120.0
found 180.0
found 145.0
found 130.0
found 150.0
found 68.00
found 80.00
found 58.00
found 96.00
found 70.00
found 145.0
found 110.0
found 145.0
found 130.0
found 110.0
found 105.0
found 100.0
found 98.00
found 180.0
found 170.0
found 190.0
found 149.0
found 78.00
found 88.00
found 75.00
found 89.00
found 63.00
found 83.00
found 67.00
found 78.00
found 97.00
found 110.0
found 110.0
found 48.00
found 66.00
found 52.00
found 70.00
found 60.00
found 110.0
found 140.0
found 139.0
found 105.0
found 95.00
found 85.00
found 88.00
found 100.0
found 90.00
found 105.0
found 85.00
found 110.0
found 120.0
found 145.0
found 165.0
found 139.0
found 140.0
found 68.00
found 95.00
found 97.00
found 75.00
found 95.00
found 105.0
found 85.00
found 97.00
found 103.0
found 125.0
found 115.0
found 133.0
found 71.00
found 68.00
found 115.0
found 85.00
found 88.00
found 90.00
found 110.0
found 130.0
found 129.0
found 138.0
found 135.0
found 155.0
found 142.0
found 125.0
found 150.0
found 71.00
found 65.00
found 80.00
found 80.00
found 77.00
found 125.0
found 71.00
found 90.00
found 70.00
found 70.00
found 65.00
found 69.00
found 90.00
found 115.0
found 115.0
found 90.00
found 76.00
found 60.00
found 70.00
found 65.00
found 90.00
found 88.00
found 90.00
found 90.00
found 78.00
found 90.00
found 75.00
found 92.00
found 75.00
found 65.00
found 105.0
found 65.00
found 48.00
found 48.00
found 67.00
found 67.00
found 67.00
found ?
found 67.00
found 62.00
found 132.0
found 100.0
found 88.00
found ?
found 72.00
found 84.00
found 84.00
found 92.00
found 110.0
found 84.00
found 58.00
found 64.00
found 60.00
found 67.00
found 65.00
found 62.00
found 68.00
found 63.00
found 65.00
found 65.00
found 74.00
found ?
found 75.00
found 75.00
found 100.0
found 74.00
found 80.00
found 76.00
found 116.0
found 120.0
found 110.0
found 105.0
found 88.00
found 85.00
found 88.00
found 88.00
found 88.00
found 85.00
found 84.00
found 90.00
found 92.00
found ?
found 74.00
found 68.00
found 68.00
found 63.00
found 70.00
found 88.00
found 75.00
found 70.00
found 67.00
found 67.00
found 67.00
found 110.0
found 85.00
found 92.00
found 112.0
found 96.00
found 84.00
found 90.00
found 86.00
found 52.00
found 84.00
found 79.00
found 82.00